drivers/kernelsu: silence warning
/tmp/optane/android_kernel_xiaomi_libra/drivers/kernelsu/throne_tracker.c:237:47: error: incompatible function pointer types initializing 'const filldir_t' (aka 'int (*const)(void *, const char *, int, long long, unsigned long long, unsigned int)') with an expression of type 'int (struct dir_context *, const char *, int, loff_t, u64, unsigned int)' (aka 'int (struct dir_context *, const char *, int, long long, unsigned long long, unsigned int)') [-Wincompatible-function-pointer-types]
  237 |                         struct my_dir_context ctx = { .ctx.actor = my_actor,
      |                                                                    ^~~~~~~~
1 error generated.

Revert "drivers/kernelsu: silence warning"

This reverts commit cdb38cc795ceaf88ba61e14d63539be426c830ea.

KernelSU: throne tracker cast my_actor to filldir_t

drivers/kernelsu/throne_tracker.c:237:47: error: incompatible function pointer types initializing 'const filldir_t' (aka 'int (*const)(void *, const char *, int, long long, unsigned long long, unsigned int)') with an expression of type 'bool (struct dir_context *, const char *, int, loff_t, u64, unsigned int)' (aka '_Bool (struct dir_context *, const char *, int, long long, unsigned long long, unsigned int)') [-Wincompatible-function-pointer-types]
  237 |                         struct my_dir_context ctx = { .ctx.actor = my_actor,
      |                                                                    ^~~~~~~~
1 error generated.